version: '3.4'

services:
    api:
        build:
            context: .
            target: development
        environment:
            - MONGODB_CONNECTION=${MONGODB_CONNECTION}
            - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
            - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
            - API_PORT=${API_PORT}
            - REDIS_USERNAME=${REDIS_USERNAME}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        command: npm run dev
